### ISSUE TITLE
Sniffable Scheduled discussions ViewAllScheduled doesn't apply to individual discussions. 

### ISSUE THREAD

**Issue by replyPUSH** [daigo75/vanilla-post-scheduler#1]
Not a biggie for me but you can technically find a scheduled discussion, by incrementing the discussion ID in an url.

**Comment by daigo75** [comment]
I'm aware of that. If you would like to fix that , please feel free to send a pull request, and I will integrate it in the main release.

The Scheduler used to be a premium (paid) plugin, which I made public because we changed our business model. Vanilla Forums is now a secondary activity to us, that's why we don't release many updates for our plugins.
